// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')

function activer(){
  document.getElementById('gauche').innerHTML ='<span class="icon-prev"></span>';
  document.getElementById('gauche').innerHTML ='<span class="icon-next"></span>';
}

function desactiver() {
  document.getElementById('gauche').innerHTML ='';
  document.getElementById('gauche').innerHTML ='';
}
